import random
name=input("enter your name")
print("hello ",name)
print("numbers are between 1 to 100.so guess the exact number the was generated by system")
def play_game():
    o=random.randint(1,100)
    print("guess the number correctly")
    i=1
    while(i<10):
        user_input=int(input("enter your guess number"))
        if(0<=user_input<=100):
            if(user_input==o):
                print("your guess is correct\n")
                print("you won the game!!..")
                break
            elif(user_input<o):
                print("your guess is too low")
                i=i+1
            elif(user_input>o):
                print("your guess is too high")
                i=i+1
        else:
            print("enter numbers between 0 to 100")
            i=i-1
    option=input("you loose.do u want to try again type yes if not no")
    if(option=="yes"):
        play_game()
    elif(option=="no"):
        print("thank you")
        exit()
play_game()
